### ISSUE TITLE
Burp Suite Community Edition package is outdated

### ISSUE THREAD

**Issue by avi12** [agabrys/chocolatey-packages#27]
According to the [download page](https://portswigger.net/burp/releases/community/latest), the latest version is 2021.2.1, whereas the latest version that the Chocolatey package supports is 2020.12.1.

**Comment by agabrys** [comment]
I pushed missing versions today:
* [2021.2](https://chocolatey.org/packages/burp-suite-free-edition/2021.2)
* [2021.2.1](https://chocolatey.org/packages/burp-suite-free-edition/2021.2.1)

**Comment by avi12** [comment]
It's great that you added support for those versions, but isn't there an automatic solution?

**Comment by agabrys** [comment]
Yes, there is an option to automate the update process. It is possible to create a script which checks for a newer version, updates the package and pushes it. It requires to configure a new Windows service which periodically executes the script ([see docs](https://docs.chocolatey.org/en-us/create/automatic-packages)).

That was the optimistic part 🙂 Now worse stuff 😉

I haven't automated it and I also don't plan to do it because I hardly use Chocolatey (I don't want to run any additional service on my PC). Some time ago I thought it is a great software, like `apt` on Debian. Unfortunately, many packages are broken, outdated or missing. The software owners are not interested to invest time and update packages of theirs software. The community is not big enough to do it too. When I started using Chocolatey I found that most of the software is unavailable (missing). I created some packages, but when I stopped using them, nobody wanted to take care of them (e.g. WebDriver/Selenium packages). At this moment I update only a few packages when I have some free time and a good mood 😄 I believe there is a huge chance that I'll stop doing it in the future. I'm a simple user and most of my software provides a built-in auto-updater (Internet browser, Office, Notepad editor etc.), so there is no need for me to use a package manager at all.

ps. I don't use Burp Suite Community Edition, so if you would like to be a maintainer - let me know 🙂

**Comment by avi12** [comment]
I don't use Burp Community Edition either; it was a one-time use to make [web-ext-deploy](https://github.com/avi12/web-ext-deploy)
I get what you mean, and I totally agree
I think that you should at least push the package to WinGet, as it is the real future of Windows software
